import { Dimensions, StyleSheet } from 'react-native';

const RAIL_WIDTH = 64;
export const NOTE_COLUMNS = 2;
const GRID_GAP = 8;
export const CARD_SIZE = (Dimensions.get('window').width - RAIL_WIDTH - 32 - GRID_GAP * (NOTE_COLUMNS - 1)) / NOTE_COLUMNS;

// Dynamic card size for configurable grid columns
export const getCardSize = (numCols: number): number => {
  return (Dimensions.get('window').width - RAIL_WIDTH - 32 - GRID_GAP * (numCols - 1)) / numCols;
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  headerSpacing: {
    paddingTop: 12,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  addButton: {
    backgroundColor: '#4CAF50',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
  },
  addButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  fab: {
    position: 'absolute',
    bottom: 32,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  fabText: {
    fontSize: 32,
    color: '#FFFFFF',
    fontWeight: '300',
    lineHeight: 36,
    marginTop: -2,
  },
  mainContentRow: {
    flex: 1,
    flexDirection: 'row',
  },
  pillRail: {
    width: RAIL_WIDTH,
    flexGrow: 0,
    backgroundColor: '#fff',
    borderRightWidth: 1,
    borderRightColor: '#e8e8e8',
  },
  pillRailContent: {
    alignItems: 'center',
    paddingVertical: 16,
  },
  tabPillGroup: {
    alignItems: 'center',
  },
  tabPill: {
    width: 32,
    height: 80,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  tabPillActive: {
    borderWidth: 2,
    borderColor: '#000',
  },
  tabPillLabelTextActive: {
    fontWeight: '800',
  },
  tabPillLabelWrapper: {
    width: 68,
    transform: [{ rotate: '-90deg' }],
  },
  tabPillLabelText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  tabPillConnector: {
    width: 0,
    height: 20,
    borderLeftWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#ccc',
  },
  tabPillAddButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(76, 175, 80, 0.08)',
  },
  tabPillAddButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#4CAF50',
    lineHeight: 20,
  },
  tabPillDivider: {
    marginTop: 20,
    alignItems: 'center',
  },
  mainContentArea: {
    flex: 1,
  },
  listContent: {
    padding: 8,
  },
  noteGrid: {
    justifyContent: 'flex-start',
    marginBottom: 8,
  },
  card: {
    width: CARD_SIZE,
    aspectRatio: 1,
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  placeholderCard: {
    backgroundColor: 'transparent',
    shadowColor: 'transparent',
    elevation: 0,
  },
  cardSvgBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardSvgBlurOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255,255,255,0.28)',
  },
  cardFrameContent: {
    position: 'absolute',
    marginTop: 12,
    // justifyContent: 'center',
  },
  cardTitleText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#333',
    // marginBottom: 4,
  },
  cardFooter: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 20,
  },
  cardDeleteButton: {
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  deleteIcon: {
    fontSize: 12,
    lineHeight: 20,
  },
  deleteButton: {
    fontSize: 24,
    color: '#999',
    marginLeft: 8,
  },
  cardType: {
    fontSize: 12,
    lineHeight: 20,
    color: '#666',
    fontStyle: 'italic',
  },
  cardContent: {
    marginBottom: 8,
    minHeight: 80,
  },
  cardPreview: {
    fontSize: 8,
    color: '#555',
    marginBottom: 4,
  },
  checklistItemPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  checklistCheck: {
    fontSize: 12,
    marginRight: 6,
    color: '#333',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  emptyText: {
    fontSize: 16,
    color: '#999',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: '90%',
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  modalCloseButton: {
    fontSize: 16,
    color: '#4CAF50',
    fontWeight: '600',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  modalSaveButton: {
    fontSize: 16,
    color: '#4CAF50',
    fontWeight: '600',
  },
  modalScroll: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  stylingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    marginBottom: 16,
  },
  stylingTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  expandIcon: {
    fontSize: 14,
    color: '#666',
  },
  colorPickerContainer: {
    marginBottom: 16,
  },
  svgToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  svgToggleLabel: {
    marginLeft: 10,
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
  },
  colorPickerDisabled: {
    opacity: 0.35,
  },
  svgDisabledHint: {
    fontSize: 12,
    color: '#999',
    fontStyle: 'italic',
    marginTop: 6,
  },
  fontPickerContainer: {
    marginBottom: 16,
  },
  fontScroll: {
    marginVertical: 8,
  },
  fontOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 6,
    marginRight: 8,
    minWidth: 80,
    alignItems: 'center',
  },
  fontOptionActive: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  fontOptionText: {
    fontSize: 12,
    color: '#333',
  },
  fontOptionTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  textStyleContainer: {
    marginBottom: 20,
  },
  textStyleButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  styleButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 6,
    alignItems: 'center',
  },
  styleButtonActive: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  styleButtonText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#666',
  },
  styleButtonTextActive: {
    color: '#fff',
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  titleInput: {
    fontSize: 18,
    fontWeight: '600',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    paddingVertical: 8,
    marginBottom: 20,
    color: '#333',
  },
  colorPicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  colorOption: {
    width: 50,
    height: 50,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  colorSelected: {
    borderWidth: 3,
    borderColor: '#333',
  },
  checkMark: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  contentTypeContainer: {
    marginBottom: 20,
  },
  typeButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  typeButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 6,
    alignItems: 'center',
  },
  typeButtonActive: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  typeButtonText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#666',
  },
  typeButtonTextActive: {
    color: '#fff',
  },
  contentInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: '#333',
    height: 150,
    marginBottom: 16,
  },
  checklistPreview: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  addChecklistItemButton: {
    marginTop: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#4CAF50',
    borderRadius: 8,
    alignItems: 'center',
  },
  addChecklistItemText: {
    color: '#fff',
    fontWeight: '700',
  },
  checklistItemEditor: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 8,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderWidth: 1,
    borderColor: '#999',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  checklistItemInput: {
    flex: 1,
    marginLeft: 8,
    paddingVertical: 6,
    fontSize: 14,
    color: '#333',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  checklistItemCompleted: {
    textDecorationLine: 'line-through',
    color: '#999',
  },
  deleteTabButton: {
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: '#ffecec',
    alignItems: 'center',
  },
  deleteTabText: {
    color: '#d9534f',
    fontWeight: '600',
  },
  modalPrimaryButton: {
    marginTop: 8,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
  },
  modalPrimaryButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  beforePicker: {
    marginVertical: 12,
  },
  dropdownToggle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#fff',
  },
  dropdownToggleText: {
    fontSize: 14,
    color: '#444',
  },
  dropdownArrow: {
    fontSize: 12,
    color: '#666',
  },
  dropdownList: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    marginTop: 8,
    backgroundColor: '#fff',
    maxHeight: 180,
  },
  dropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dropdownItemActive: {
    backgroundColor: '#4CAF50',
  },
  dropdownItemText: {
    fontSize: 14,
    color: '#444',
  },
  dropdownItemTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  readOnlyContent: {
    fontSize: 14,
    color: '#444',
    lineHeight: 20,
    marginBottom: 8,
  },
});